### ISSUE TITLE
Blocked by Cloudflare

### ISSUE THREAD

**Issue by webcoreinc** [UraraReika/jwb-products-grid-load-more#5]
hey bro Cloudflare is blocking installation.

Rule message
Adobe ColdFusion - Dangerous File Upload - CVE:CVE-2019-7816

Think we are going to pass and find another solution for load more. We are not really trusting your coding.

Best of luck.

**Comment by UraraReika** [comment]
Hello @webcoreinc! Thanks for the feedback.

This is not problem of plugins code as you can think in the first place looking at the error description. This plugin has been repeatedly tested and is used by dozens of people on different sites.

If you devote more time to this problem, you will be able to understand its ambiguity, taking into account all the official references to it, for example, as in the example you provided - https://github.com/advisories/GHSA-fj36-mv52-w6p7. 

> The "unrestricted file upload" term is used in vulnerability databases and elsewhere, but it is insufficiently precise. The phrase could be interpreted as the lack of restrictions on the size or number of uploaded files, which is a resource consumption issue.

You can also refer to Cloudflare's official documentation, which states that it blocks the download of .zip files - https://developers.cloudflare.com/firewall/cf-firewall-rules/actions. This is due to the fact that Cloudflare cannot predict the types and content of the files that the archive contains, and therefore blocks it completely. You can also read several posts on this topic on their forum - https://community.cloudflare.com/t/manged-rule-blocking-wordpress-plugin-uploads/449749 and https://community.cloudflare.com/t/cloudflre-is-blocking-me-from-uploading-plugins-to-my-wordpress-site/419158.

These posts also describe how people tried to work around similar problems. If you still do not trust, you can try to upload any .zip file to your site, the result will be appropriate.

And also relatively soon, a universal solution will appear in the Crocoblock plug-in line for this case.

Thank you for your understanding.
